# Fly.io deployment configuration
app = "batch-code-service"
primary_region = "lax"  # Los Angeles - change to your preferred region

[build]

[deploy]
  release_command = "echo 'Starting deployment...'"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.tcp_checks]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[metrics]
  port = 9091
  path = "/metrics"

# Health checks
[[checks]]
  grace_period = "5s"
  interval = "60s"
  method = "get"
  path = "/api/health"
  port = 3000
  timeout = "10s"
  type = "http"

# Secrets (set with: fly secrets set KEY=value)
# WEBHOOK_SECRET
# SENTRY_DSN
